package com.nikoladronjak.rently.domain;

import java.util.Objects;

import jakarta.persistence.*;

/**
 * Represents a domain class for storing information about a Owner entity. This
 * class is mapped to the "Owners" table in the database using JPA annotations.
 * The primary key of this table is "ownerId".
 * 
 * The Owner entity contains an ownerId, a first name, a last name, an email
 * address, a password and a phone number.
 * 
 * @author Nikola Dronjak
 */
@Entity
@Table(name = "Owners")
public class Owner {

	/**
	 * Represents a unique identifier for the owner (int). This identifier is
	 * automatically generated by JPA.
	 */
	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	private int ownerId;

	/**
	 * Represents the first name of the owner (String).
	 */
	private String firstName;

	/**
	 * Represents the last name of the owner (String).
	 */
	private String lastName;

	/**
	 * Represents the email address of the owner (String). The email address has to
	 * be unique.
	 */
	@Column(unique = true)
	private String email;

	/**
	 * Represents the password of the owner (String).
	 */
	private String password;

	/**
	 * Represents the phone number of the owner (String).
	 */
	private String phoneNumber;

	public Owner() {

	}

	public Owner(int ownerId, String firstName, String lastName, String email, String password, String phoneNumber) {
		this.ownerId = ownerId;
		this.firstName = firstName;
		this.lastName = lastName;
		this.email = email;
		this.password = password;
		this.phoneNumber = phoneNumber;
	}

	public int getOwnerId() {
		return ownerId;
	}

	public void setOwnerId(int ownerId) {
		this.ownerId = ownerId;
	}

	public String getFirstName() {
		return firstName;
	}

	public void setFirstName(String firstName) {
		this.firstName = firstName;
	}

	public String getLastName() {
		return lastName;
	}

	public void setLastName(String lastName) {
		this.lastName = lastName;
	}

	public String getEmail() {
		return email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public String getPassword() {
		return password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	public String getPhoneNumber() {
		return phoneNumber;
	}

	public void setPhoneNumber(String phoneNumber) {
		this.phoneNumber = phoneNumber;
	}

	@Override
	public String toString() {
		return "Owner [ownerId=" + ownerId + ", firstName=" + firstName + ", lastName=" + lastName + ", email=" + email
				+ ", password=" + password + ", phoneNumber=" + phoneNumber + "]";
	}

	@Override
	public int hashCode() {
		return Objects.hash(email, firstName, lastName, ownerId, password, phoneNumber);
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		Owner other = (Owner) obj;
		return Objects.equals(email, other.email) && Objects.equals(firstName, other.firstName)
				&& Objects.equals(lastName, other.lastName) && ownerId == other.ownerId
				&& Objects.equals(password, other.password) && Objects.equals(phoneNumber, other.phoneNumber);
	}
}
