package com.nikoladronjak.rently.domain;

import java.util.List;
import java.util.Objects;
import java.util.stream.Collectors;

import jakarta.persistence.*;

/**
 * Represents a domain class for storing information about a Property entity.
 * This class is mapped to the "Properties" table in the database using JPA
 * annotations. The primary key of this table is "propertyId".
 * 
 * The Property entity contains a propertyId, a name of the property, a street
 * address of the property, a description of the property, a monthly rental
 * rate, the size of the property, an isAvailable flag, the number of parking
 * spots, a list of photos of the property, an owner associated with the
 * Property entity and a list of leases associated with the Property entity.
 * 
 * This entity represents a superclass for the following entities:
 * <ul>
 * <li>Residence</li>
 * <li>EventSpace</li>
 * <li>OfficeSpace</li>
 * </ul>
 * 
 * @author Nikola Dronjak
 */
@Entity
@Table(name = "Properties")
@Inheritance(strategy = InheritanceType.JOINED)
public class Property {

	/**
	 * Represents a unique identifier for the property (int). This identifier is
	 * automatically generated by JPA.
	 */
	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	private int propertyId;

	/**
	 * Represents the name of the property (String).
	 */
	private String name;

	/**
	 * Represents the street address of the property (String). The street address
	 * has to be unique.
	 */
	@Column(unique = true)
	private String address;

	/**
	 * Represents the description of the property (String).
	 */
	private String description;

	/**
	 * Represents the monthly rental rate of the property (double).
	 */
	private double rentalRate;

	/**
	 * Represents the size of the property in square meters (int).
	 */
	private int size;

	/**
	 * Indicates whether the property is available (boolean).
	 * <ul>
	 * <li>True - The property is available.</li>
	 * <li>False - The property is not available.</li>
	 * </ul>
	 */
	private boolean isAvailable;

	/**
	 * Represents the number of parking spaces that come with the property (int).
	 */
	private int numberOfParkingSpots;

	/**
	 * Represents the list of photos of the property (List&lt;String&gt;).
	 * 
	 * The photos are stored in a separate table called "PropertyPhotos".
	 */
	@ElementCollection(fetch = FetchType.EAGER)
	private List<String> photos;

	/**
	 * Represents the owner who is associated the property (Owner).
	 */
	@ManyToOne
	@JoinColumn(name = "ownerId")
	private Owner owner;

	/**
	 * Represents the list of leases with which the property is associated
	 * (List&lt;Lease&gt;).
	 */
	@OneToMany(mappedBy = "property")
	private List<Lease> leases;

	public Property() {

	}

	public Property(int propertyId, String name, String address, String description, double rentalRate, int size,
			boolean isAvailable, int numberOfParkingSpots, List<String> photos, Owner owner, List<Lease> leases) {
		this.propertyId = propertyId;
		this.name = name;
		this.address = address;
		this.description = description;
		this.rentalRate = rentalRate;
		this.size = size;
		this.isAvailable = isAvailable;
		this.numberOfParkingSpots = numberOfParkingSpots;
		this.photos = photos;
		this.owner = owner;
		this.leases = leases;
	}

	public int getPropertyId() {
		return propertyId;
	}

	public void setPropertyId(int propertyId) {
		this.propertyId = propertyId;
	}

	public String getName() {
		return name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getAddress() {
		return address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

	public String getDescription() {
		return description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public double getRentalRate() {
		return rentalRate;
	}

	public void setRentalRate(double rentalRate) {
		this.rentalRate = rentalRate;
	}

	public int getSize() {
		return size;
	}

	public void setSize(int size) {
		this.size = size;
	}

	public boolean isAvailable() {
		return isAvailable;
	}

	public void setAvailable(boolean isAvailable) {
		this.isAvailable = isAvailable;
	}

	public int getNumberOfParkingSpots() {
		return numberOfParkingSpots;
	}

	public void setNumberOfParkingSpots(int numberOfParkingSpots) {
		this.numberOfParkingSpots = numberOfParkingSpots;
	}

	public List<String> getPhotos() {
		return photos;
	}

	public void setPhotos(List<String> photos) {
		this.photos = photos;
	}

	public Owner getOwner() {
		return owner;
	}

	public void setOwner(Owner owner) {
		this.owner = owner;
	}

	public List<Lease> getLeases() {
		return leases;
	}

	public void setLeases(List<Lease> leases) {
		this.leases = leases;
	}

	@Override
	public String toString() {
		return "Property [propertyId=" + propertyId + ", name=" + name + ", address=" + address + ", description="
				+ description + ", rentalRate=" + rentalRate + ", size=" + size + ", isAvailable=" + isAvailable
				+ ", numberOfParkingSpots=" + numberOfParkingSpots + ", photos=" + String.join(", ", photos)
				+ ", owner=" + owner + ", leases="
				+ leases.stream().map(Lease::toString).collect(Collectors.joining(", ")) + "]";
	}

	@Override
	public int hashCode() {
		return Objects.hash(address, description, isAvailable, leases, name, numberOfParkingSpots, owner, photos,
				propertyId, rentalRate, size);
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		Property other = (Property) obj;
		return Objects.equals(address, other.address) && Objects.equals(description, other.description)
				&& isAvailable == other.isAvailable && Objects.equals(leases, other.leases)
				&& Objects.equals(name, other.name) && numberOfParkingSpots == other.numberOfParkingSpots
				&& Objects.equals(owner, other.owner) && Objects.equals(photos, other.photos)
				&& propertyId == other.propertyId
				&& Double.doubleToLongBits(rentalRate) == Double.doubleToLongBits(other.rentalRate)
				&& size == other.size;
	}
}
