package com.nikoladronjak.rently.domain;

import java.util.ArrayList;
import java.util.List;
import java.util.Objects;

import jakarta.persistence.*;
import jakarta.validation.constraints.*;

/**
 * Represents a domain class for storing information about a Property entity.
 * This class is mapped to the "Properties" table in the database using JPA
 * annotations. The primary key of this table is "propertyId".
 * 
 * The Property entity contains a propertyId, a name of the property, a street
 * address of the property, a description of the property, a monthly rental
 * rate, the size of the property, an isAvailable flag, the number of parking
 * spots, a list of photos of the property, an owner associated with the
 * Property entity and a list of leases associated with the Property entity.
 * 
 * This entity represents a superclass for the following entities:
 * <ul>
 * <li>Residence</li>
 * <li>EventSpace</li>
 * <li>OfficeSpace</li>
 * </ul>
 * 
 * @author Nikola Dronjak
 */
@Entity
@Table(name = "Properties")
@Inheritance(strategy = InheritanceType.JOINED)
public class Property {

	/**
	 * Represents a unique identifier for the property (int). This identifier is
	 * automatically generated by JPA.
	 */
	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	private int propertyId;

	/**
	 * Represents the name of the property (String).
	 * 
	 * The name cannot be null and it has to have at least 5 characters.
	 */
	@NotBlank(message = "The name of the property is required.")
	@Size(min = 5, message = "The name of the property has to have at least 5 characters.")
	private String name;

	/**
	 * Represents the street address of the property (String). The street address
	 * has to be unique.
	 * 
	 * The street address cannot be null and it has to have at least 5 characters.
	 */
	@NotBlank(message = "The address of the property is required.")
	@Size(min = 5, message = "The address of the property has to have at least 5 characters.")
	@Column(unique = true)
	private String address;

	/**
	 * Represents the description of the property (String).
	 * 
	 * The description cannot be null (but it can be empty).
	 */
	@NotNull(message = "The description of the property is required.")
	private String description;

	/**
	 * Represents the monthly rental rate of the property (Double).
	 * 
	 * The rental rate cannot be null and it has to be a positive value (greater
	 * than 0).
	 */
	@NotNull(message = "The rental rate of the property is required.")
	@Positive(message = "The rental rate of the property has to be a positive value.")
	private Double rentalRate;

	/**
	 * Represents the size of the property in square meters (Integer).
	 * 
	 * The size cannot be null and it has to be a positive value (greater than 0).
	 */
	@NotNull(message = "The size of the property is required.")
	@Positive(message = "The size of the property has to be a positive value.")
	private Integer size;

	/**
	 * Indicates whether the property is available (Boolean).
	 * <ul>
	 * <li>True - The property is available.</li>
	 * <li>False - The property is not available.</li>
	 * </ul>
	 * 
	 * The isAvailable flag cannot be null.
	 */
	@NotNull(message = "You have to specify wether the property is available or not.")
	private Boolean isAvailable;

	/**
	 * Represents the number of parking spaces that come with the property
	 * (Integer).
	 * 
	 * The number of parking spots cannot be null and it has to be a positive value
	 * (0 or greater).
	 */
	@NotNull(message = "The number of parking spots for the property is required.")
	@Min(value = 0, message = "The number of parking spots for the property has to be a positive value.")
	private Integer numberOfParkingSpots;

	/**
	 * Represents the list of photos of the property (List&lt;String&gt;).
	 * 
	 * The photos are stored in a separate table called "PropertyPhotos".
	 * 
	 * The list of photos cannot be null. There must be at least 1 photo of the
	 * property and there can't be more than 15 photos of the property.
	 */
	@NotNull(message = "The photos of the property are required.")
	@Size(min = 0, max = 15, message = "There has to be atleast 1 photo of the property and there cant be more than 15 photos of the property.")
	@ElementCollection(fetch = FetchType.EAGER)
	private List<String> photos;

	/**
	 * Represents the owner who is associated the property (Owner).
	 * 
	 * The id of the owner cannot be null.
	 */
	@NotNull(message = "You have to specify the owner of the property.")
	@ManyToOne
	@JoinColumn(name = "ownerId")
	private Owner owner;

	/**
	 * Represents the list of leases with which the property is associated
	 * (List&lt;Lease&gt;).
	 */
	@OneToMany(mappedBy = "property")
	private List<Lease> leases;

	public Property() {
		this.photos = new ArrayList<>();
	}

	public Property(int propertyId, String name, String address, String description, Double rentalRate, Integer size,
			Boolean isAvailable, Integer numberOfParkingSpots, List<String> photos, Owner owner, List<Lease> leases) {
		this.propertyId = propertyId;
		this.name = name;
		this.address = address;
		this.description = description;
		this.rentalRate = rentalRate;
		this.size = size;
		this.isAvailable = isAvailable;
		this.numberOfParkingSpots = numberOfParkingSpots;
		this.photos = (photos != null) ? photos : new ArrayList<>();
		this.owner = owner;
		this.leases = leases;
	}

	public int getPropertyId() {
		return propertyId;
	}

	public void setPropertyId(int propertyId) {
		this.propertyId = propertyId;
	}

	public String getName() {
		return name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getAddress() {
		return address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

	public String getDescription() {
		return description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public Double getRentalRate() {
		return rentalRate;
	}

	public void setRentalRate(Double rentalRate) {
		this.rentalRate = rentalRate;
	}

	public Integer getSize() {
		return size;
	}

	public void setSize(Integer size) {
		this.size = size;
	}

	public Boolean isAvailable() {
		return isAvailable;
	}

	public void setAvailable(Boolean isAvailable) {
		this.isAvailable = isAvailable;
	}

	public Integer getNumberOfParkingSpots() {
		return numberOfParkingSpots;
	}

	public void setNumberOfParkingSpots(Integer numberOfParkingSpots) {
		this.numberOfParkingSpots = numberOfParkingSpots;
	}

	public List<String> getPhotos() {
		return photos;
	}

	public void setPhotos(List<String> photos) {
		this.photos = photos;
	}

	public Owner getOwner() {
		return owner;
	}

	public void setOwner(Owner owner) {
		this.owner = owner;
	}

	public List<Lease> getLeases() {
		return leases;
	}

	public void setLeases(List<Lease> leases) {
		this.leases = leases;
	}

	@Override
	public String toString() {
		return "Property [propertyId=" + propertyId + ", name=" + name + ", address=" + address + ", description="
				+ description + ", rentalRate=" + rentalRate + ", size=" + size + ", isAvailable=" + isAvailable
				+ ", numberOfParkingSpots=" + numberOfParkingSpots + ", photos=" + photos + ", owner=" + owner
				+ ", leases=" + leases + "]";
	}

	@Override
	public int hashCode() {
		return Objects.hash(address, description, isAvailable, leases, name, numberOfParkingSpots, owner, photos,
				propertyId, rentalRate, size);
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		Property other = (Property) obj;
		return Objects.equals(address, other.address) && Objects.equals(description, other.description)
				&& Objects.equals(isAvailable, other.isAvailable) && Objects.equals(leases, other.leases)
				&& Objects.equals(name, other.name) && Objects.equals(numberOfParkingSpots, other.numberOfParkingSpots)
				&& Objects.equals(owner, other.owner) && Objects.equals(photos, other.photos)
				&& propertyId == other.propertyId && Objects.equals(rentalRate, other.rentalRate)
				&& Objects.equals(size, other.size);
	}
}
