package com.nikoladronjak.rently.domain;

import java.util.List;
import java.util.Objects;
import java.util.stream.Collectors;

import jakarta.persistence.*;
import jakarta.validation.constraints.*;

/**
 * Represents a domain class for storing information about a Utility entity.
 * This class is mapped to the "Utilities" table in the database using JPA
 * annotations. The primary key of this table is "utilityId".
 * 
 * The Utility entity contains a utilityId, a name of the utility, a description
 * of the utility and a list of utility leases which are associated with the
 * Utility entity.
 * 
 * @author Nikola Dronjak
 */
@Entity
@Table(name = "Utilities")
public class Utility {

	/**
	 * Represents a unique identifier for the utility (int). This identifier is
	 * automatically generated by JPA.
	 */
	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	private int utilityId;

	/**
	 * Represents the name of the utility (String). The name has to be unique.
	 * 
	 * The name cannot be null and it has to have at least 5 characters.
	 */
	@NotBlank(message = "The name of the utility is required.")
	@Size(min = 5, message = "The name of the utility has to have at least 5 characters.")
	@Column(unique = true)
	private String name;

	/**
	 * Represents the description of the utility (String).
	 * 
	 * The description cannot be null (but it can be empty).
	 */
	@NotNull(message = "The description of the utility is required.")
	private String description;

	/**
	 * Represents the list of utility leases with which the utility is associated
	 * (List&lt;UtilityLease&gt;).
	 */
	@OneToMany(mappedBy = "utility")
	private List<UtilityLease> utilityLeases;

	public Utility() {

	}

	public Utility(int utilityId, String name, String description, List<UtilityLease> utilityLeases) {
		this.utilityId = utilityId;
		this.name = name;
		this.description = description;
		this.utilityLeases = utilityLeases;
	}

	public int getUtilityId() {
		return utilityId;
	}

	public void setUtilityId(int utilityId) {
		this.utilityId = utilityId;
	}

	public String getName() {
		return name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getDescription() {
		return description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public List<UtilityLease> getUtilityLeases() {
		return utilityLeases;
	}

	public void setUtilityLeases(List<UtilityLease> utilityLeases) {
		this.utilityLeases = utilityLeases;
	}

	@Override
	public String toString() {
		return "Utility [utilityId=" + utilityId + ", name=" + name + ", description=" + description
				+ ", utilityLeases="
				+ utilityLeases.stream().map(UtilityLease::toString).collect(Collectors.joining(", ")) + "]";
	}

	@Override
	public int hashCode() {
		return Objects.hash(description, name, utilityId, utilityLeases);
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		Utility other = (Utility) obj;
		return Objects.equals(description, other.description) && Objects.equals(name, other.name)
				&& utilityId == other.utilityId && Objects.equals(utilityLeases, other.utilityLeases);
	}
}
